<!DOCTYPE html>
<html>
  <head>
    <title>PSA</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="core/fonts/mono.css"> 
    <link rel="stylesheet" type="text/css" href="core/css/animate.css"> 
    <link rel="stylesheet" type="text/css" href="core/css/cinescript.css"> 
    <link rel="stylesheet" type="text/css" href="core/css/style_core.css"> 
    <link rel="stylesheet" type="text/css" href="core/css/mermaid.css"> 
    <link rel="stylesheet" type="text/css" href="core/css/gitgraph.css"> 
    <link rel="stylesheet" type="text/css" href="core/css/style_ensiie.css"> 
  </head>
  <body>
    <textarea id="source" readonly>

layout: true
class: animated fadeIn middle numbers

.footnote[
`PSA` - N. Dubray - ENSIIE - 2018 - [:book:](../index.html)
]

---

# Errors and exceptions

.shadow.hcenter.w45[![](images/null-pointer-exception.png)]
.hcenter[[source: thomaskausch.wordpress.com](https://thomaskausch.wordpress.com/2017/07/13/nil-null-nsnull-optionals/)]

---

# Errors and exceptions

## Runtime errors
:arrow_right: when a program encounters unusual execution conditions, errors can happen **at runtime**.

## Examples: external causes
* the system runs out of memory,
* a file can not be opened because it has been deleted,
* hardware error,
* etc...

## Examples: internal causes
* a division by zero occurs during the evaluation of an expression,
* "double free",
* **error-prone implementation**,
* etc...

## Severity level
* a **benign error** should not perturb the program final output, should spawn an **info message**,
* a **small error** may perturb the program final output, should spawn a **warning message**,
* a **serious error** will perturb the program final output, should spawn an **error message**,
* a **disastrous error** prevents the program from continuing, should spawn a .red.bold[critical error message].

---

# Errors and exceptions

## Possible ways to react to a runtime error

1. **do nothing**: the program will have an **unexpected behavior** (result OK, segfault, etc...),
2. print an error message on `stderr` and exit,
3. set a flag or return an **error code**, try to continue the program execution if possible.

:warning: runtime errors will not always cause visible effects.

## Common misconception
.alert[
if modifying a "working" program leads to a bad behavior, then **there must be a bug in the modified parts of the code**.
]

:warning: This deduction is **NOT ALWAYS TRUE**.  

* some runtime errors have no visible side effect until a different portion of the code is reached.
* you never know when a program is "working".

## Golden rules

:arrow_right: consider that no program is bug-free,  
:arrow_right: remember that some runtime errors may not have side effects **NOW**.

---

# Errors and exceptions

## Error codes
:arrow_right: returning an error code in case of a runtime error may seem to be a good solution, **but**
* each library may define its own error codes,
* every function call should be followed by a test to know if an error happened, to break the program's flow,
* the return value of a function may be used to do something else than returning error codes,
* separating the handling of runtime errors and the implementation is hard.

## `C++` Exceptions

:arrow_right: provide a **standard** mechanism to handle runtime errors.

:+: very important when mixing libraries,  
:+: allow to break the program's flow on runtime errors,  
:warning: may induce an overhead if exceptions are frequent.

---

# Exception handling in `C++`

## The four parts of exception handling mechanism
1. Identify a runtime problem (**hit** the exception)
2. Inform your calling function (**throw** the exception)
3. Receive the error information (**catch** the exception)
4. Decide what to do (**handle** the exception)

## `try`
:arrow_right: defines a **code block** from which some exceptions should be catched.

## `throw`
:arrow_right: throw an exception of a given type, then jump to the **first corresponding `catch` block** (if any).

## `catch`
:arrow_right: defines a **code block** to handle a given exception type thrown from the `try` code block.

---

# Exception handling in `C++`

## .hcenter[\[example0.cpp\]]
```C++
double func0(int a, int b)
{
  if (b == 0) // hit
  {
    throw b;  // throw
  }
}

try
{
  double v0 = func0(3, 1);
  double v1 = func0(2, 0);
  double v2 = func0(5, 0);
}

catch(int a)  // catch
{
  std::cout << "division by zero error" << std::endl; // handle
}
```

## .hcenter[Shell session]
```shell
$ g++ example0.cpp -o example0
$ ./example0
division by zero error
```

---

# Exception handling in `C++`

## Catch several exceptions

:arrow_right: provide several `catch` blocks with different types.

```C++
try                   { do_something(); }
catch (int i)         { handle0();      }
*catch (double v)      { handle1();      }
*catch (std::string s) { handle2();      }
```

:arrow_right: allows to handle different exceptions differently.

## Catch all exceptions

:arrow_right: provide a special `catch(...)` block.

```C++
try                   { do_something(); }
catch (int i)         { handle0();      }
catch (double v)      { handle1();      }
catch (std::string s) { handle2();      }
*catch (...)           { handle3();      }
```

:arrow_right: can be used as a "default" catch.

---

# Exception handling in `C++`

## Exception rethrowing

:arrow_right: when throwing an exception from a `catch` block.  
:arrow_right: simply use `throw` to rethrow the exception.

```C++
try
{
  do_something0();

  try
  {
    do_something1();
  }
  catch (myType a)
  {
    handle0();
*   throw;
  }
}
catch (myType b)
{
  handle1();
}
```

---

# Exception handling in `C++`

## .hcenter[\[example1.cpp\]]
```C++
#include <iostream>

double func0(int a, int b) { if (a == 0) throw 3; return 0.0; }

double func1(int a, int b)
{
  double r = 0.0;
  try
  {
    r = func0(0, b);
    std::cout << "normal execution" << std::endl;
  }
  catch(int i)
  {
    std::cout << "catch in func1" << std::endl;
*   throw;
  }
  return r;
}

int main(int argc, char ** argv)
{
  try { func1(0,1); }
  catch(int) { std::cout << "catch in main" << std::endl; }
  return 0;
}
```

## .hcenter[Shell session]
```shell
$ g++ example1.cpp -o example1
$ ./example1
catch in func0
catch in main
```


---

# Exception handling in `C++`

## Restricting exception types

:arrow_right: it is possible to specify the exception types a function can throw.

```C++
int func0(double a) throw(int, double)
{
  if (a < 0.0) throw 2; // int
  else throw 3.0; // double
  return 0.0; // good luck with that...
}
```

---

TODO

default exception types

---

TODO

custom exception types

---

TODO

inheritance and custom exception types

---

TODO

:warning: Do NOT test parameters with exceptions

---

TODO

exceptions in python

---

TODO

exception through swig

    </textarea>

    <script src="core/javascript/remark.js"></script>
    <script src="core/javascript/plotly.js" type="text/javascript"></script>
    <script src="core/javascript/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML&delayStartupUntil=configured" type="text/javascript"></script>
    <script src="core/javascript/emojify.js" type="text/javascript"></script>
    <script src="core/javascript/mermaid.js" type="text/javascript"></script>
    <script src="core/javascript/term.js" type="text/javascript"></script>
    <script src="core/javascript/jquery-2.1.1.min.js" type="text/javascript"></script>
    <script src="core/javascript/extend-jquery.js" type="text/javascript"></script>
    <script src="core/javascript/cinescript.js" type="text/javascript"></script>
    <script src="core/javascript/gitgraph.js" type="text/javascript"></script>
    <script>

    // === Remark.js initialization ===
    var slideshow = remark.create({
      highlightStyle: 'monokai',
      countIncrementalSlides: false,
      highlightLines: true,
      highlightInlineCode: false
    });

    // === Mermaid.js initialization ===
    mermaid.initialize({
      startOnLoad: false,
      cloneCssStyles: false,
      flowchart:{
        height: 50
      },
      sequenceDiagram:{
        width: 110,
        height: 30
      }
    });

    function initMermaid(s) {
      var diagrams = document.querySelectorAll('.mermaid');
      var i;
      for(i=0;i<diagrams.length;i++){
        if(diagrams[i].offsetWidth>0){
          mermaid.init(undefined, diagrams[i]);
        }
      }
    }

    slideshow.on('afterShowSlide', initMermaid);
    initMermaid(slideshow.getSlides()[slideshow.getCurrentSlideIndex()]);

    // === MathJax.js initialization ===
    MathJax.Hub.Config({ tex2jax: { skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'] } }); 
    MathJax.Hub.Queue(function() { $(MathJax.Hub.getAllJax()).map(function(index, elem) { return(elem.SourceElement()); }).parent().addClass('has-jax'); });
    MathJax.Hub.Configured();

    // === Emojify.js initialization ===
    emojify.run();

    // === Cinescript initialization ===
    $(document).ready(init_cinescripts);

    </script>
  </body>
</html>

